name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Expo CLI and dependencies
      run: |
        npm install -g expo-cli
        npm ci
    
    - name: Prebuild Expo Android Project
      run: |
        npx expo prebuild --platform android --clean
    
    - name: Inspect Android Project Structure
      run: |
        cd android
        echo "Listing all .gradle files:"
        find . -name "*.gradle"
        echo "\nAndroid project structure:"
        tree -L 3
        echo "\nChecking build.gradle contents:"
        cat app/build.gradle
    
    - name: Validate Gradle Configuration
      run: |
        cd android
        ./gradlew help \
          --warning-mode all \
          -Porg.gradle.warning.mode=all \
          -Porg.gradle.logging.level=info
    
    - name: Build Android APK with Verbose Logging
      run: |
        cd android
        # Detailed build command with maximum verbosity
        ./gradlew assembleRelease \
          -Pandroid.injected.build.model.only.versioned=3 \
          -Pandroid.useAndroidX=true \
          -Pandroid.enableJetifier=true \
          -Porg.gradle.caching=true \
          -Porg.gradle.parallel=false \
          -Porg.gradle.warning.mode=all \
          -Porg.gradle.logging.level=debug \
          --stacktrace \
          --info \
          --debug
    
    - name: Diagnose APK Build Issues
      if: failure()
      run: |
        cd android
        echo "Checking Gradle build cache:"
        ls -la ~/.gradle
        
        echo "\nChecking Android SDK:"
        ls -la /usr/local/lib/android/sdk
        
        echo "\nChecking Android project dependencies:"
        ./gradlew dependencies
        
        echo "\nChecking build configuration:"
        ./gradlew properties
    
    - name: Upload APK Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build-diagnostics
        path: |
          android/app/build/outputs/
          android/build/
          android/app/build/reports/
          android/app/build/tmp/
        retention-days: 5
