name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Expo CLI and dependencies
      run: |
        npm install -g expo-cli
        npm ci
        npm install -g npm-check-updates
    
    - name: Check Dependency Versions
      run: |
        echo "Node.js version:"
        node --version
        echo "\nNPM version:"
        npm --version
        echo "\nExpo CLI version:"
        expo --version
        echo "\nDependency check:"
        npm-check-updates
    
    - name: Diagnose Prebuild Environment
      run: |
        pwd
        ls -la
        echo "\nContents of android directory:"
        ls -la android || echo "Android directory not found"
    
    - name: Prepare Gradle Wrapper
      run: |
        cd android
        chmod +x gradlew || echo "Could not set execute permissions on gradlew"
        ls -l gradlew*
    
    - name: Prebuild Expo Android Project
      run: |
        npx expo prebuild --platform android || {
          echo "Prebuild failed. Checking project structure..."
          pwd
          ls -la
          echo "\nNode modules:"
          ls -la node_modules
          echo "\nExpo config:"
          cat app.json
          exit 1
        }
    
    - name: List Project Structure
      run: |
        echo "Root directory:"
        ls -la
        echo "\nAndroid directory:"
        ls -la android
        echo "\nGradle files:"
        find android -name "*.gradle"
    
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
    
    - name: Build Android APK
      run: |
        cd android
        # Capture detailed build output
        ./gradlew assembleRelease \
          -Pandroid.useAndroidX=true \
          -Pandroid.enableJetifier=true \
          -Porg.gradle.caching=true \
          -Porg.gradle.parallel=false \
          -Porg.gradle.workers.max=2 \
          -Porg.gradle.configureondemand=false \
          --stacktrace \
          --info \
          --warning-mode all \
          2>&1 | tee build-output.log
        
        # Check build output for specific errors
        grep -E "ERROR|FAILURE" build-output.log && exit 1
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
    
    - name: Diagnose Build Failure
      if: failure()
      run: |
        echo "Detailed error diagnosis:"
        cd android
        echo "\nBuild output log:"
        cat build-output.log
        echo "\nGradle daemon logs:"
        find ~/.gradle -name "*.log" -type f -print -exec cat {} \;
        echo "\nSystem information:"
        uname -a
        java -version
    
    - name: Upload Build Diagnostics
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-diagnostics
        path: |
          android/build-output.log
          android/app/build/outputs/
          android/build/
          android/app/build/reports/
          android/app/build/tmp/
        retention-days: 5
    
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: meter-reader-release
        path: |
          android/app/build/outputs/apk/release/*.apk
          android/app/build/outputs/mapping/release/mapping.txt
        retention-days: 5
    
    - name: Print Gradle Daemon Logs
      if: always()
      run: |
        cd android
        find ~/.gradle -name "*.log" -type f -print -exec cat {} \;
    
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: meter-reader-release
        path: |
          android/app/build/outputs/apk/release/*.apk
          android/app/build/outputs/mapping/release/mapping.txt
        retention-days: 5
    
    - name: Upload Build Diagnostics
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-diagnostics
        path: |
          android/app/build/outputs/
          android/build/
          android/app/build/reports/
          android/app/build/tmp/
        retention-days: 5
