name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install Expo CLI and dependencies
      run: |
        npm install -g expo-cli
        npm ci
    
    - name: Diagnose Prebuild Environment
      run: |
        pwd
        ls -la
        echo "\nContents of android directory:"
        ls -la android
    
    - name: Prepare Gradle Wrapper
      run: |
        cd android
        # Ensure Gradle wrapper has correct permissions
        chmod +x gradlew
        chmod +x gradlew.bat
        ls -l gradlew*
    
    - name: Prebuild Expo Android Project
      run: |
        npx expo prebuild --platform android
    
    - name: Diagnose Prebuild Results
      run: |
        pwd
        ls -la
        echo "\nContents of android directory after prebuild:"
        ls -la android
    
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2
    
    - name: Build Android APK
      run: |
        cd android
        # Explicitly use ./gradlew with full path
        /bin/bash -c "./gradlew assembleRelease \
          -Pandroid.useAndroidX=true \
          -Pandroid.enableJetifier=true \
          -Porg.gradle.caching=true \
          -Porg.gradle.parallel=true \
          -Porg.gradle.configureondemand=true \
          --stacktrace \
          --info \
          --scan"
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
    
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: meter-reader-release
        path: |
          android/app/build/outputs/apk/release/*.apk
          android/app/build/outputs/mapping/release/mapping.txt
        retention-days: 5
    
    - name: Upload Build Diagnostics
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-diagnostics
        path: |
          android/app/build/outputs/
          android/build/
          android/app/build/reports/
          android/app/build/tmp/
        retention-days: 5
