name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Ensure full git history for proper Gradle wrapper validation
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g expo-cli
    
    - name: Prepare Gradle Wrapper
      run: |
        cd android
        # Ensure Gradle wrapper has correct permissions
        chmod +x ./gradlew
        chmod +x gradlew
        ls -l gradlew
    
    - name: Diagnose System Environment
      run: |
        echo "Java Version:"
        java -version
        echo "\nNode.js Version:"
        node --version
        echo "\nNPM Version:"
        npm --version
        echo "\nExpo CLI Version:"
        expo --version
    
    - name: Prebuild Android project
      run: |
        npx expo prebuild --platform android
        
    - name: List Android Project Structure
      run: |
        cd android
        find . -type d
        echo "\nGradle Files:"
        find . -name "*.gradle"
        
    - name: Check Gradle and Kotlin versions
      run: |
        cd android
        ./gradlew --version || cat ./gradlew
        
    - name: Build Android APK with maximum verbosity
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace --info --debug
      env:
        JAVA_HOME: ${{ steps.setup-java.outputs.path }}
    
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/*.apk
        retention-days: 5
    
    - name: Upload Comprehensive Build Logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-diagnostics
        path: |
          android/app/build/outputs/
          android/build/
          android/app/build/reports/
          android/app/build/tmp/
        retention-days: 5
